---

  - name: install all the required Packages
    apt: 
      name: "{{ discourse_debs }}" 
      state: installed
    
  - name: Create the discourse directory
    file:
      path: /var/discourse
      state: directory
      owner: root
      group: root

  - git:
      repo: git@github.com:discourse/discourse.git
      dest: /var/discourse
      clone: yes

